/* Cozy Tavern — regex-styles.js
 * M34: the 🎨 pack — the writer's SillyTavern display styles, shipped as
 * built-in display rules so a fresh coat is already dressed: the bracketed
 * header as a card, the trackers folded, NPC thoughts marked, the cut-away
 * boxed. Display-mode only: the page keeps its words. Generated from the
 * writer's own regex export; the TWB pair is replaced by a self-closing rule.
 */

export const STYLE_PACK = [
  {
    "id": "style-twb",
    "name": "🎨 The World Beyond (the cut-away, boxed)",
    "find": "\\*\\*\\*\\s*The World Beyond\\s*\\*\\*\\*\\s*\\n(?:\\s*(\\[[^\\]\\n]*\\])\\s*\\n)?([^\\n][\\s\\S]*?)(?=\\n\\s*\\n|$)",
    "flags": "g",
    "replace": "<details style=\"margin:12px 0;border:1px solid #353545;border-radius:6px;overflow:hidden;background:#15101a;\" open><summary style=\"padding:8px 14px;font-size:0.75em;text-transform:uppercase;letter-spacing:0.15em;font-weight:700;color:#c9a24e;font-family:Georgia,serif;border-bottom:1px solid #252530;list-style:none;text-align:center;cursor:pointer;\">✦ The World Beyond ✦</summary><div style=\"color:#7a7a8a;font-size:0.75em;text-align:center;padding:6px 10px;border-bottom:1px solid #252530;\">$1</div><div style=\"padding:8px 14px;color:#d8d0c4;font-size:0.9em;line-height:1.5;font-style:italic;\">$2</div></details>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": "The house’s own version: it boxes the marker, the optional [Location — Day, Time] line, and the paragraph that follows, and closes itself. (The SillyTavern pair relied on a tracker block coming after it.)"
  },
  {
    "id": "style-header-6-pipe",
    "name": "🎨 Header (6-pipe)",
    "find": "^([^\\[\\]|\\n]{5,}?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)$",
    "flags": "gm",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"display:flex;gap:10px;margin-top:4px;flex-wrap:wrap;\"><span style=\"color:#c9a24e;font-size:0.78em;\">$2</span><span style=\"background:#1a1a20;padding:1px 6px;border-radius:3px;font-family:monospace;font-size:0.72em;color:#d4842a;\">$3</span></div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$4</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $5</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $6</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-header-5-dash",
    "name": "🎨 Header (5-dash)",
    "find": "\\[(?!IST:|ACW:|VOICE:|CROWD:)([^\\[\\]|\\n]+?)\\s*[—–-]{1,3}\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"color:#c9a24e;font-size:0.78em;margin-top:3px;\">$2</div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$3</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $4</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $5</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-header-5-pipes-location-date-time-weather-attire-position",
    "name": "🎨 Header (5 pipes: Location — Date | Time | Weather | Attire | Position)",
    "find": "^\\[(?!IST:|ACW:|VOICE:|CROWD:)([^\\[\\]|\\n]+?)\\s*[—–-]{1,3}\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\]$",
    "flags": "gm",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"display:flex;gap:10px;margin-top:4px;flex-wrap:wrap;\"><span style=\"color:#c9a24e;font-size:0.78em;\">$2</span><span style=\"background:#1a1a20;padding:1px 6px;border-radius:3px;font-family:monospace;font-size:0.72em;color:#d4842a;\">$3</span></div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$4</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $5</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $6</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-scene-header-6-pipe-bracketed",
    "name": "🎨 Scene Header (6-pipe, bracketed)",
    "find": "^\\[(?!IST:|ACW:|VOICE:|CROWD:)([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\]$",
    "flags": "gm",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"display:flex;gap:10px;margin-top:4px;flex-wrap:wrap;\"><span style=\"color:#c9a24e;font-size:0.78em;\">$2</span><span style=\"background:#1a1a20;padding:1px 6px;border-radius:3px;font-family:monospace;font-size:0.72em;color:#d4842a;\">$3</span></div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$4</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $5</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $6</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-scene-header-5-field-with-dash",
    "name": "🎨 Scene Header (5-field with dash)",
    "find": "^\\[(?!IST:|ACW:|VOICE:|CROWD:)([^\\[\\]|\\n]+?)\\s*[—–-]{1,3}\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\]$",
    "flags": "gm",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"display:flex;gap:10px;margin-top:4px;flex-wrap:wrap;\"><span style=\"color:#c9a24e;font-size:0.78em;\">$2</span><span style=\"background:#1a1a20;padding:1px 6px;border-radius:3px;font-family:monospace;font-size:0.72em;color:#d4842a;\">$3</span></div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$4</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $5</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $6</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-header-5-field-location-date-time-weather-attire-position",
    "name": "🎨 Header (5-field: Location — Date | Time | Weather | Attire | Position)",
    "find": "^\\[(?!IST:|ACW:|VOICE:|CROWD:)([^|\\]\\n]+?)\\s*—\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\]",
    "flags": "gm",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"display:flex;gap:10px;margin-top:4px;flex-wrap:wrap;\"><span style=\"color:#c9a24e;font-size:0.78em;\">$2</span><span style=\"background:#1a1a20;padding:1px 6px;border-radius:3px;font-family:monospace;font-size:0.72em;color:#d4842a;\">$3</span></div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$4</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $5</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $6</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-header-6-pipes-location-date-time-weather-attire-position",
    "name": "🎨 Header (6 pipes: Location | Date | Time | Weather | Attire | Position)",
    "find": "^\\[(?!IST:|ACW:|VOICE:|CROWD:)([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\s*\\|\\s*([^\\[\\]|\\n]+?)\\]$",
    "flags": "gm",
    "replace": "<div style=\"background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 40%,#1a1f25 100%);border-left:3px solid #d45246;padding:10px 14px;margin:4px 0 8px 0;border-radius:0 6px 6px 0;\"><div style=\"color:#e8e8f4;font-size:0.92em;font-variant:small-caps;letter-spacing:0.5px;font-family:Georgia,serif;font-weight:700;\">📍 $1</div><div style=\"display:flex;gap:10px;margin-top:4px;flex-wrap:wrap;\"><span style=\"color:#c9a24e;font-size:0.78em;\">$2</span><span style=\"background:#1a1a20;padding:1px 6px;border-radius:3px;font-family:monospace;font-size:0.72em;color:#d4842a;\">$3</span></div><div style=\"display:flex;justify-content:space-between;margin-top:4px;padding-top:4px;border-top:1px solid rgba(201,168,76,0.1);gap:8px;flex-wrap:wrap;\"><span style=\"color:#6b9ec4;font-size:0.72em;font-style:italic;\">$4</span><span style=\"color:#c78a96;font-size:0.72em;font-style:italic;\">👕 $5</span><span style=\"color:#8a7ab4;font-size:0.72em;font-style:italic;width:100%;text-align:right;\">🧭 $6</span></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-npc-thoughts",
    "name": "🎨 NPC Thoughts",
    "find": "(?:\\*?~?\\*?t\\*?~\\*?(.*?)\\*?~\\*?[\\/\\\\]?t\\*?~?\\*?|\\*~t~(.*?)~[\\/\\\\]?t~\\*)",
    "flags": "g",
    "replace": "<span style=\"padding:1px 4px;border-left:2px solid rgba(138,122,180,0.4);border-radius:0 2px 2px 0;background:rgba(138,122,180,0.06);\"><em style=\"color:#9a8abc;\">$1$2</em></span>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-pulse-open-closed-default",
    "name": "🎨 PULSE Open (closed default)",
    "find": "\\{PULSE\\}",
    "flags": "g",
    "replace": "<details style=\"margin:10px 0;background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 100%);border:1px solid rgba(212,82,70,0.3);border-radius:4px;overflow:hidden;\"><summary style=\"padding:8px 14px;color:#d45246;font-family:Georgia,serif;font-variant:small-caps;font-weight:700;font-size:0.9em;letter-spacing:1.5px;text-align:center;cursor:pointer;border-bottom:1px solid rgba(212,82,70,0.2);list-style:none;\">⚡ Scene Pulse</summary>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-pulse-close",
    "name": "🎨 PULSE Close",
    "find": "\\{\\/\\s*PULSE\\s*\\}",
    "flags": "g",
    "replace": "</details>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-crowd-full",
    "name": "🎨 CROWD Full",
    "find": "\\[CROWD:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(212,82,70,0.05);border:1px solid rgba(212,82,70,0.12);border-radius:3px;padding:6px 10px;margin:5px 8px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:4px;\"><div style=\"color:#d45246;font-size:0.75em;font-weight:700;font-variant:small-caps;\">👥 $1</div><div style=\"color:#e0d8cc;font-size:0.8em;font-style:italic;\">$2 · $3</div><div style=\"color:#c0b8a8;font-size:0.78em;font-style:italic;width:100%;margin-top:2px;\">$4</div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-crowd-nopipe",
    "name": "🎨 CROWD NoPipe",
    "find": "\\[CROWD:\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(212,82,70,0.05);border:1px solid rgba(212,82,70,0.12);border-radius:3px;padding:6px 10px;margin:5px 8px;display:flex;align-items:center;gap:4px;\"><div style=\"color:#d45246;font-size:0.75em;font-weight:700;font-variant:small-caps;\">👥 $1</div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-ist-full",
    "name": "🎨 IST Full",
    "find": "\\[IST:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*P:([\\d\\-]+)\\s+R:([\\d\\-]+)\\s+S:([\\d\\-]+)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(255,255,255,0.03);border:1px solid rgba(212,82,70,0.15);border-radius:3px;padding:8px 10px;margin:5px 8px;\"><div style=\"color:#e8e0d8;font-family:Georgia,serif;font-weight:700;font-size:1em;padding-bottom:4px;margin-bottom:6px;border-bottom:1px solid rgba(212,82,70,0.12);\">$1</div><div style=\"display:flex;gap:6px;margin-bottom:6px;flex-wrap:wrap;\"><div style=\"flex:1;min-width:70px;background:rgba(0,0,0,0.25);border:1px solid rgba(212,82,70,0.1);border-radius:2px;padding:3px 6px;\"><div style=\"color:#d47060;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;font-weight:600;\">Mood</div><div style=\"color:#e0d8cc;font-size:0.85em;font-style:italic;\">$2</div></div><div style=\"flex:1;min-width:70px;background:rgba(0,0,0,0.25);border:1px solid rgba(212,82,70,0.1);border-radius:2px;padding:3px 6px;\"><div style=\"color:#d47060;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;font-weight:600;\">Toward MC</div><div style=\"color:#e0d8cc;font-size:0.85em;font-style:italic;\">$3</div></div><div style=\"flex:1;min-width:70px;background:rgba(0,0,0,0.25);border:1px solid rgba(212,82,70,0.1);border-radius:2px;padding:3px 6px;\"><div style=\"color:#d47060;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;font-weight:600;\">Agenda</div><div style=\"color:#e0d8cc;font-size:0.85em;font-style:italic;\">$4</div></div></div><div style=\"display:flex;align-items:center;gap:5px;margin:2px 0;\"><div style=\"color:#c9a24e;font-size:0.7em;font-weight:700;font-variant:small-caps;min-width:10px;\">P</div><div style=\"flex:1;height:5px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;\"><div style=\"width:$5%;height:100%;border-radius:3px;background:linear-gradient(90deg,#8a7a4a,#c9a84c);\"></div></div><div style=\"color:#c0b8a0;font-size:0.7em;min-width:18px;text-align:right;\">$5</div></div><div style=\"display:flex;align-items:center;gap:5px;margin:2px 0;\"><div style=\"color:#c9a24e;font-size:0.7em;font-weight:700;font-variant:small-caps;min-width:10px;\">R</div><div style=\"flex:1;height:5px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;\"><div style=\"width:$6%;height:100%;border-radius:3px;background:linear-gradient(90deg,#8a3a3a,#d45246);\"></div></div><div style=\"color:#c0b8a0;font-size:0.7em;min-width:18px;text-align:right;\">$6</div></div><div style=\"display:flex;align-items:center;gap:5px;margin:2px 0;\"><div style=\"color:#c9a24e;font-size:0.7em;font-weight:700;font-variant:small-caps;min-width:10px;\">S</div><div style=\"flex:1;height:5px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;\"><div style=\"width:$7%;height:100%;border-radius:3px;background:linear-gradient(90deg,#5a3a8a,#8a7ab4);\"></div></div><div style=\"color:#c0b8a0;font-size:0.7em;min-width:18px;text-align:right;\">$7</div></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-ist-no-towardmc",
    "name": "🎨 IST No TowardMC",
    "find": "\\[IST:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*P:([\\d\\-]+)\\s+R:([\\d\\-]+)\\s+S:([\\d\\-]+)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(255,255,255,0.03);border:1px solid rgba(212,82,70,0.15);border-radius:3px;padding:8px 10px;margin:5px 8px;\"><div style=\"color:#e8e0d8;font-family:Georgia,serif;font-weight:700;font-size:1em;padding-bottom:4px;margin-bottom:6px;border-bottom:1px solid rgba(212,82,70,0.12);\">$1</div><div style=\"display:flex;gap:6px;margin-bottom:6px;flex-wrap:wrap;\"><div style=\"flex:1;min-width:70px;background:rgba(0,0,0,0.25);border:1px solid rgba(212,82,70,0.1);border-radius:2px;padding:3px 6px;\"><div style=\"color:#d47060;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;font-weight:600;\">Mood</div><div style=\"color:#e0d8cc;font-size:0.85em;font-style:italic;\">$2</div></div><div style=\"flex:1;min-width:70px;background:rgba(0,0,0,0.25);border:1px solid rgba(212,82,70,0.1);border-radius:2px;padding:3px 6px;\"><div style=\"color:#d47060;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;font-weight:600;\">Agenda</div><div style=\"color:#e0d8cc;font-size:0.85em;font-style:italic;\">$3</div></div></div><div style=\"display:flex;align-items:center;gap:5px;margin:2px 0;\"><div style=\"color:#c9a24e;font-size:0.7em;font-weight:700;font-variant:small-caps;min-width:10px;\">P</div><div style=\"flex:1;height:5px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;\"><div style=\"width:$4%;height:100%;border-radius:3px;background:linear-gradient(90deg,#8a7a4a,#c9a84c);\"></div></div><div style=\"color:#c0b8a0;font-size:0.7em;min-width:18px;text-align:right;\">$4</div></div><div style=\"display:flex;align-items:center;gap:5px;margin:2px 0;\"><div style=\"color:#c9a24e;font-size:0.7em;font-weight:700;font-variant:small-caps;min-width:10px;\">R</div><div style=\"flex:1;height:5px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;\"><div style=\"width:$5%;height:100%;border-radius:3px;background:linear-gradient(90deg,#8a3a3a,#d45246);\"></div></div><div style=\"color:#c0b8a0;font-size:0.7em;min-width:18px;text-align:right;\">$5</div></div><div style=\"display:flex;align-items:center;gap:5px;margin:2px 0;\"><div style=\"color:#c9a24e;font-size:0.7em;font-weight:700;font-variant:small-caps;min-width:10px;\">S</div><div style=\"flex:1;height:5px;background:rgba(255,255,255,0.08);border-radius:3px;overflow:hidden;\"><div style=\"width:$6%;height:100%;border-radius:3px;background:linear-gradient(90deg,#5a3a8a,#8a7ab4);\"></div></div><div style=\"color:#c0b8a0;font-size:0.7em;min-width:18px;text-align:right;\">$6</div></div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-ist-empty",
    "name": "🎨 IST Empty",
    "find": "\\[IST:\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(255,255,255,0.03);border:1px solid rgba(212,82,70,0.1);border-radius:3px;padding:6px 10px;margin:5px 8px;color:#8a8078;font-family:Georgia,serif;font-style:italic;font-size:0.8em;text-align:center;\">$1</div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-acw-open",
    "name": "🎨 ACW Open",
    "find": "\\{WATCHLIST\\}",
    "flags": "g",
    "replace": "<details style=\"margin:10px 0;background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 100%);border:1px solid rgba(74,156,140,0.3);border-radius:4px;overflow:hidden;\"><summary style=\"padding:8px 14px;color:#4a9c8c;font-family:Georgia,serif;font-variant:small-caps;font-weight:700;font-size:0.9em;letter-spacing:1.5px;text-align:center;cursor:pointer;border-bottom:1px solid rgba(74,156,140,0.2);list-style:none;\">👁 Active Watchlist</summary>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-acw-close",
    "name": "🎨 ACW Close",
    "find": "\\{\\/\\s*WATCHLIST\\s*\\}",
    "flags": "g",
    "replace": "</details>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-acw-full",
    "name": "🎨 ACW Full",
    "find": "\\[ACW:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*\\[?r:([^|\\]\\n]+?)\\]?\\s*\\|\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(255,255,255,0.03);border:1px solid rgba(74,156,140,0.12);border-left:2px solid rgba(74,156,140,0.35);border-radius:2px;padding:7px 11px;margin:4px 8px;\"><div style=\"display:flex;align-items:baseline;gap:8px;margin-bottom:3px;\"><span style=\"font-size:0.85em;\">$5</span><span style=\"color:#e0dcd4;font-family:Georgia,serif;font-weight:700;font-size:0.92em;letter-spacing:0.3px;\">$1</span><span style=\"color:#4a9c8c;font-size:0.7em;font-style:italic;\">— $3</span><span style=\"flex:1;\"></span><span style=\"color:#4a9c8c;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;opacity:0.7;\">$6</span></div><div style=\"color:#c0b8a8;font-size:0.78em;font-style:italic;line-height:1.35;margin-bottom:2px;\">$2</div><div style=\"color:#a09888;font-size:0.72em;font-style:italic;\">↳ $4</div><div style=\"color:#706858;font-size:0.63em;font-style:italic;margin-top:3px;opacity:0.75;\">$7</div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-acw-no-agenda",
    "name": "🎨 ACW No Agenda",
    "find": "\\[ACW:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*\\[?r:([^|\\]\\n]+?)\\]?\\s*\\|\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"background:rgba(255,255,255,0.03);border:1px solid rgba(74,156,140,0.12);border-left:2px solid rgba(74,156,140,0.35);border-radius:2px;padding:7px 11px;margin:4px 8px;\"><div style=\"display:flex;align-items:baseline;gap:8px;margin-bottom:3px;\"><span style=\"font-size:0.85em;\">$4</span><span style=\"color:#e0dcd4;font-family:Georgia,serif;font-weight:700;font-size:0.92em;letter-spacing:0.3px;\">$1</span><span style=\"color:#4a9c8c;font-size:0.7em;font-style:italic;\">— $3</span><span style=\"flex:1;\"></span><span style=\"color:#4a9c8c;font-size:0.6em;font-variant:small-caps;letter-spacing:1px;opacity:0.7;\">$5</span></div><div style=\"color:#c0b8a8;font-size:0.78em;font-style:italic;line-height:1.35;margin-bottom:2px;\">$2</div><div style=\"color:#706858;font-size:0.63em;font-style:italic;margin-top:3px;opacity:0.75;\">$6</div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-voices-open",
    "name": "🎨 VOICES Open",
    "find": "\\{VOICES\\}",
    "flags": "g",
    "replace": "<details style=\"margin:10px 0;background:linear-gradient(135deg,#1a1a25 0%,#1f1a28 100%);border:1px solid rgba(138,122,180,0.3);border-radius:4px;overflow:hidden;\"><summary style=\"padding:8px 14px;color:#8a7ab4;font-family:Georgia,serif;font-variant:small-caps;font-weight:700;font-size:0.9em;letter-spacing:1.5px;text-align:center;cursor:pointer;border-bottom:1px solid rgba(138,122,180,0.2);list-style:none;\">💬 Voices</summary>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-voices-close",
    "name": "🎨 VOICES Close",
    "find": "\\{\\/\\s*VOICES\\s*\\}",
    "flags": "g",
    "replace": "</details>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-voice-4-field",
    "name": "🎨 VOICE 4-field",
    "find": "\\[VOICE:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"border-left:2px solid rgba(138,122,180,0.25);padding:4px 10px;margin:4px 8px;\"><div style=\"display:flex;justify-content:space-between;align-items:center;\"><div style=\"color:#e0dcd4;font-weight:700;font-size:0.85em;\">$1 $2</div><div style=\"color:#5a5a6a;font-size:0.6em;font-style:italic;\">$3</div></div><div style=\"color:#c8c0b8;font-size:0.82em;margin-top:2px;\">$4</div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  },
  {
    "id": "style-voice-3-field",
    "name": "🎨 VOICE 3-field",
    "find": "\\[VOICE:\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^|\\]\\n]+?)\\s*\\|\\s*([^\\]\\n]+?)\\s*\\]",
    "flags": "g",
    "replace": "<div style=\"border-left:2px solid rgba(138,122,180,0.25);padding:4px 10px;margin:4px 8px;\"><div style=\"display:flex;justify-content:space-between;align-items:center;\"><div style=\"color:#e0dcd4;font-weight:700;font-size:0.85em;\">$1 $2</div></div><div style=\"color:#c8c0b8;font-size:0.82em;margin-top:2px;\">$3</div></div>",
    "on": "storyteller",
    "mode": "display",
    "enabled": true,
    "builtin": true,
    "pack": "styles",
    "note": ""
  }
];
