/* Cozy Tavern — the in-repo harness (M9, A8).
 * Run it: node tests/harness/run.mjs */
import './stack.mjs';
import './store.mjs';
import './engine.mjs';
import './agents.mjs';
import './referee.mjs';
import './providers.mjs';
import './tablock.mjs';
import './source.mjs';
import './housekeeper.mjs';
import './showrunners.mjs';
import './finishing.mjs';
import './beauty.mjs';
import './assign.mjs';
import './m22.mjs';
import './books.mjs';
import './polish.mjs';
import './projects.mjs';
import './findability.mjs';
import './m21.mjs';
import './m28.mjs';
import './m29.mjs';
import './m30.mjs';
import './m31.mjs';
import './m32.mjs';
import './m33.mjs';
import './m34.mjs';
import './m35.mjs';
import './m36.mjs';
import './m37.mjs';
import './m38.mjs';
import './m40.mjs';
import './m41.mjs';
import './m43.mjs';
import './m44.mjs';
import './m45.mjs';
import './m46.mjs';
import './m47.mjs';
import './m48.mjs';
import './m49.mjs';
import './m50.mjs';
import './m52.mjs';
import './m53.mjs';
import './m57.mjs';
import { runAll } from './lib.mjs';

console.log('Cozy Tavern — harness');
await runAll();
